id: 1
cfg: ''
batch_size: 8
data: /home/zhang/FL_Projects/exp/fedyolo/data/coco128.yaml
device: 0
weights: yolov5s.pt
hyp: data/hyps/hyp.scratch-low.yaml
imgsz: 640
epochs: 2
freeze:
- 10
nosave: true
cache: ram
noval: true
workers: 6
project: runs/train
name: coco128
exist_ok: false
label_smoothing: 0.0
patience: 100
multi_scale: false
save_dir: runs/train/coco128/client1
